### PR TITLE
Add peas

### PR DESCRIPTION
**Pull request by deikatsuo**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Do you need it to generate a lib? (funny I was notified for this lib...)

cc @EPashkin

**Comment by EPashkin** [comment]
Currently all updates better get from Artful
Also we really need these packages in this repo?

**Comment by EPashkin** [comment]
Also IMHO if it added to `dl.sh` and updated with it then no problem with maintaining extra girs and we can accept it.

**Comment by GuillaumeGomez** [comment]
Good point!

**Comment by bilelmoussaoui** [comment]
I believe this is not really useful as it is not part of the "core" gir files

**Pull request closed without merging**
