### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Not sure if we want to merge it before the release though.

cc @EPashkin @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
IMHO better not include this script in current release,
at minimum debian's pango gir-files need some work to be loaded by Gir

**Comment by sdroege** [comment]
Doesn't affect the release as only the GTK4-related files are updated or not? So let's just do it afterwards.

>  at minimum debian's pango gir-files need some work to be loaded by Gir

But they're not changed as part of this PR?

**Comment by EPashkin** [comment]
Sorry, I readed script wrong, it not attempt to read old packages from ubuntu's server.
Still line 20917 of Gtk-4.0.gir changed badly, seems current fix.sh removes type name
```diff
@@ -22030,24 +20914,22 @@ than when a loading function was called.</doc>
         </return-value>
         <parameters>
           <parameter name="section" transfer-ownership="none">
-            <doc xml:space="preserve" filename="../gtk/gtkcssprovider.c" line="192">section the error happened in</doc>
-            <type name="CssSection"/>
+            <doc xml:space="preserve">section the error happened in</doc>
+            <type/>
           </parameter>
```

**Comment by sdroege** [comment]
>  Still line 20917 of Gtk-4.0.gir changed badly, seems current fix.sh removes type name

It's known to be broken. That's fixed by https://gitlab.gnome.org/GNOME/gtk/merge_requests/1173 and will be in the next release.

**Comment by bilelmoussaoui** [comment]
This one is no longer needed I suppose

**Pull request closed without merging**
