### PR TITLE
GIR file for libappindicator3

### PR DESCRIPTION
**Pull request by bkhl**
Added file from https://packages.ubuntu.com/artful/libappindicator-dev

Had to add package name myself as it's missing in the original.

First step towards adding libappindicator3 support, a pull request for gtk-rs/sys is also coming

### CODE REVIEW

**Comment by EPashkin** [comment]
Linux only package?

**Comment by bkhl** [comment]
I think so.

**Comment by EPashkin** [comment]
Don't forget add it do `dl.sh`

I slightly against adding not cross-platform files to this,
but final decision up to @GuillaumeGomez.

**Comment by EPashkin** [comment]
And, please, when adding to `dl.sh` add also comment with link to repository, that it used,
this helps on updates.

**Comment by bkhl** [comment]
Added to dl.sh

Not sure what you mean by link to repository. The libappindicator upstream repository? In dl.sh or in the commit message?

**Comment by EPashkin** [comment]
Link to your repository, that using this AppIndicator3-0.1.gir
Comment to dl.sh before download call and better with extra empty line before it.

**Comment by bkhl** [comment]
Ah, my plan was to make another pull request to gtk-rs/sys once we get past this one.

For now it's in a branch at https://github.com/bkhl/sys

**Comment by EPashkin** [comment]
I almost sure that we don't include `appindicator-sys` in our `sys` as in not cross-platform.
Usually syses just included in normal repos (https://github.com/bkhl/appindicator in your case) as sub crate or have separate repo.
We collected many to https://github.com/gtk-rs/sys just to minimize number of repositories, that we need maintain.
It this PR will be not accepted, nothing will stop you from just use your `gir-files` fork instead :wink:

**Comment by GuillaumeGomez** [comment]
@EPashkin: Do we handle correctly specific platform gir files?

**Comment by EPashkin** [comment]
@GuillaumeGomez As I know there no platform specific in gir files, just library that it describe not cross platform.

**Comment by GuillaumeGomez** [comment]
So we're back to adding a parameter into the gir file in order to specify the targetted platform?

**Comment by GuillaumeGomez** [comment]
Also I'm wondering: why do you want this to be in `gtk-rs/sys` @bhkl? Can't you have it on your own and handle this by yourself? Might be simpler for you, no?

**Comment by EPashkin** [comment]
@GuillaumeGomez, Sorry, don't understand reason to do that and why do you ask.
I just against include non cross-platform modules in `gtk-rs` (mostly about `sys`).

**Comment by GuillaumeGomez** [comment]
Well, I still don't understand the point of this PR for the moment...

**Comment by bkhl** [comment]
I will just bundle it up in bkhl/appindicator then.

Thanks for the input.

**Pull request closed without merging**
