### PR TITLE
fix type name for JSGlobalContextRef

### PR DESCRIPTION
**Pull request by vhdirk**
This is needed to make https://github.com/gtk-rs/webkit2gtk-webextension-rs/pull/39 reproducible

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍

**Comment by EPashkin** [comment]
@vhdirk Can you fix webkit too?
Something like this if it works and generated code still run fine
```
xmlstarlet ed -P -L \
	-i '//_:type[not(@name) and @c:type="JSGlobalContextRef"]' -t 'attr' -n 'name' -v "JavaScriptCore.GlobalContext" \
	-i '//_:type[not(@name) and @c:type="JSValueRef"]' -t 'attr' -n 'name' -v "JavaScriptCore.Value" \
	WebKit2-4.0.gir
```

**Comment by EPashkin** [comment]
also `not(@name)` better added to remove duplicate on second run

**Comment by vhdirk** [comment]
I still have to double-check if the generated code actually works.
Also, the exact command used to generate the -sys crates does not seem to be included in any makefile?

**Comment by vhdirk** [comment]
The last commit makes makes regeneration work out of the box again for both webkit2gtk and webkit2gtk-webextension.

**Comment by EPashkin** [comment]
@vhdirk Instead updating JavaScriptCore-4.0.gir in fix.sh can you just revert changes in it made in 092fb83e14c84b987cbe5068338cbfd973a1bf43 and comment line in dl.sh?
Then only thing IMHO missing in PR is actual changes in WebKit2-4.0.gir and WebKit2WebExtension-4.0.gir

> Also, the exact command used to generate the -sys crates does not seem to be included in any makefile?

You right, I use external script in Windows, so missed that.
```
cargo run --release -- -c D:\eap\rust\0\webkit2gtk-rs\gir-webkit2.toml -d D:\eap\rust\0\gir-files -o D:\eap\rust\0\webkit2gtk-rs\webkit2gtk-sys || exit /b 1
cargo run --release -- -c D:\eap\rust\0\webkit2gtk-rs\Gir.toml -d D:\eap\rust\0\gir-files -o D:\eap\rust\0\webkit2gtk-rs || exit /b 1
cargo run --release -- -c D:\eap\rust\0\webkit2gtk-webextension-rs\gir-webkit2gtk-webextensions.toml -d D:\eap\rust\0\gir-files -o D:\eap\rust\0\webkit2gtk-webextension-rs\webkit2gtk-webextension-sys || exit /b 1
cargo run --release -- -c D:\eap\rust\0\webkit2gtk-webextension-rs\Gir.toml -d D:\eap\rust\0\gir-files -o D:\eap\rust\0\webkit2gtk-webextension-rs || exit /b 1
```

**Comment by EPashkin** [comment]
@vhdirk Your version generated? My version need `JSCContext` in `webkit_frame_get_js_context` (not sure that it right as I can check that it really works)
And please remove inner merge
```diff
--- a/JavaScriptCore-4.0.gir
+++ b/JavaScriptCore-4.0.gir
@@ -2,6 +2,7 @@
 <repository xmlns="http://www.gtk.org/introspection/core/1.0" xmlns:c="http://www.gtk.org/introspection/c/1.0" version="1.2">
   <namespace name="JavaScriptCore" version="4.0" shared-library="javascriptcoregtk-4.0" c:identifier-prefixes="JS" c:symbol-prefixes="JS">
     <record name="GlobalContext" c:type="JSGlobalContextRef" foreign="1"/>
+    <record name="Context" c:type="JSCContext" foreign="1"/>
     <record name="Value" c:type="JSValueRef" foreign="1"/>
   </namespace>
 </repository>
```

**Comment by EPashkin** [comment]
@vhdirk Ignore "and please remove inner merge". Sorry, I fetched merged version of PR instead normal.
But JSContext still needed for webkit2gtk-webextension-rs
```
> D:\eap\rust\0\gir>cargo run --release -- -c D:\eap\rust\0\webkit2gtk-webextension-rs\gir-webkit2gtk-webextensions.toml -d D:\eap\rust\0\gir-files -o D:\eap\rust\0\webkit2gtk-webextension-rs\webkit2gtk-webextension-sys
thread 'main' panicked at 'Incomplete library, unresolved: ["JavaScriptCore.Context"]', src\library_postprocessing.rs:58:13
```

**Comment by vhdirk** [comment]
@EPashkin I will, but I've stumbled upon something weird now:

When using this to generate webkit2gtk-webextension, it is complaning that the types for ```Value``` do not match.

```
 WARN 2019-03-23T08:03:24Z: libgir::codegen::sys::ffi_type: [c:type mismatch `JSCValue` != `JSValueRef` of `Value`]
```

So, I though I'd just replace ```JSValueRef``` with ```JSCValue```. That solves the error for webextension, but then when I try to regenerate webkit2gtk itself, it's just the other way around:

```
 WARN 2019-03-23T08:07:12Z: libgir::codegen::sys::ffi_type: [c:type mismatch `JSValueRef` != `JSCValue` of `Value`]
```

**Comment by EPashkin** [comment]
From new JavaScriptCore-4.0.gir `Value` really `JSCValue`
`<class name="Value" c:symbol-prefix="value" c:type="JSCValue" parent="GObject.Object">`
but no JSValueRef in it, so just we can just define it yourself
`<record name="ValueRef" c:type="JSValueRef" foreign="1"/>`
add use it in webkit2-4.0.gir fix instead `"JavaScriptCore.Value"`

**Comment by EPashkin** [comment]
.. and update javascriptcore-sys to have
`pub type JSCValue = *mut c_void;`

**Comment by EPashkin** [comment]
..maybe with some functions from https://github.com/WebKit/webkit/blob/master/Source/JavaScriptCore/API/glib/JSCValue.h

**Comment by EPashkin** [comment]
Part of https://github.com/gtk-rs/webkit2gtk-rs/issues/48

**Comment by EPashkin** [comment]
@GuillaumeGomez This IMHO ready for merge, PR javascript-rs based on it merged

**Comment by GuillaumeGomez** [comment]
Indeed, thanks!

**Pull request merged**
