### PR TITLE
Update GdkPixbuf gir files

### PR DESCRIPTION
**Pull request by pbor**
https://github.com/gtk-rs/gtk-rs/issues/241

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by sdroege** [comment]
Please run `fix.sh`. That should also fix up the formatting :)

**Comment by pbor** [comment]
`fix.sh` did not do anything, but `reformat.sh` did the trick :)

**Review by sdroege — APPROVED** [review]
Looks reasonable. Ideally you'd first check if the gdk-pixbuf-sys` and non-`sys` can be generated properly from this and the changes make sense.

Can you create a WIP PR for that based on these .gir files? If no further fixes are needed this can get in then.

**Comment by pbor** [comment]
It seems to choke on `gmodule`... I added `GModule` to `external_libraries` in `Gir.toml`, but that does not seems to be enough...

**Pull request merged**
