### PR TITLE
Update

### PR DESCRIPTION
**Pull request by EPashkin**
Added script to mass download. Updated from ubuntu Artful.

cc @GuillaumeGomez, @antoyo, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Wo, awesome! Huge 👍 for me. Thanks!

**Comment by sdroege** [comment]
This fixes https://github.com/gtk-rs/gir-files/issues/6

And looks good to me, thanks :)

**Comment by sdroege** [comment]
Need to be careful when regenerating, especially for global functions that are added

**Comment by GuillaumeGomez** [comment]
I merge then. Thanks again @EPashkin!

**Pull request merged**
