### PR TITLE
bump gtk4 gir files to 4.5-ish

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
@sdroege feel free to go ahead and merge this, will refresh the gir files once a new release of pango is out that contains a fix for the `pango_font_get_languages` method. Otherwise the rest looks good to me.

**Comment by sdroege** [comment]
Can you fix that one locally then so we can get pango done? :)

**Comment by bilelmoussaoui** [comment]
> Can you fix that one locally then so we can get pango done? :)

I will override it on pango's side and drop the override once a new snapshot is released

**Comment by sdroege** [comment]
Works for me

**Pull request merged**
