### PR TITLE
Add Notify-0.7.gir

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
cc @EPashkin

**Comment by EPashkin** [comment]
Same as others ;)

**Comment by GuillaumeGomez** [comment]
And same answer. :p

**Comment by hasufell** [comment]
Hello

**Comment by EPashkin** [comment]
@hasufell Sorry, it was unclear: currently we add there only .gir for libs that we maintains.

**Comment by EPashkin** [comment]
See https://github.com/gtk-rs/gir-files/pull/12 for more discussion

**Comment by GuillaumeGomez** [comment]
Indeed, and we refuse it. We already have a lot of libraries to maintain. If you need help to generate the bindings, just ask us, we can help you. Thanks anyway!

**Pull request closed without merging**
