### PR TITLE
gdk4 wayland fixes

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
otherwise we can't map those types to the ones in wayland-rs-sys
Needed for https://github.com/gtk-rs/gtk4-rs/pull/46

cc @sdroege @GuillaumeGomez

### CODE REVIEW

**Review by sdroege — APPROVED** [review]
Sounds good to me.

We should really map those "unknown pointer types" automatically to a `*mut c_void` or similar instead of just giving up...

**Comment by bilelmoussaoui** [comment]
> Sounds good to me.
> 
> We should really map those "unknown pointer types" automatically to a `*mut c_void` or similar instead of just giving up...

I'm not sure what would be the better way to handle it?

**Comment by bilelmoussaoui** [comment]
Ah right, from gir instead, makes sense I guess. Currently it doesn't fail, it's just you can't find those types; maybe we can overwrite them manually in gdk4wayland-sys?

**Comment by sdroege** [comment]
If that's supported by gir, sure. I don't think it is and I think it's already before it applies the config that it currently fails?

**Comment by bilelmoussaoui** [comment]
It doesn't fail at all currently :/ It just generates a broken -sys lib

**Comment by bilelmoussaoui** [comment]
@sdroege do you mind merging this one? I need it to provide a new gtk4 feature in my fdo portals crate

**Comment by GuillaumeGomez** [comment]
Then let's go!

**Pull request merged**
