### PR TITLE
Added GUDev

### PR DESCRIPTION
**Pull request by hfiguiere**
Use this for the gudev crate and I maintained a fork for that.

### CODE REVIEW

**Comment by hfiguiere** [comment]
The file come libgudev-devel 234-1.fc33

**Comment by sdroege** [comment]
As the gudev bindings are not part of gtk-rs, why do you want to have the .gir file here? Usually you'd keep it in your repository in that case, like e.g. gstreamer-rs does.

**Comment by hfiguiere** [comment]
The idea was to avoid copying them all and use the submodule since apparently gir expect to have them all in the same directory.

**Comment by sdroege** [comment]
Ok, what do you think @GuillaumeGomez @bilelmoussaoui ?

**Comment by bilelmoussaoui** [comment]
I do that for sourceview, libhandy since forever. You can copy your gir file on the fly by modifying the generator script a bit but I don't think it makes sense to add more gir files

**Comment by GuillaumeGomez** [comment]
If it's not used in gtk-rs, then it doesn't belong here.

**Comment by sdroege** [comment]
Maybe it would be useful to allow specifying multiple gir file directories to gir

**Comment by GuillaumeGomez** [comment]
We could, in case a file isn't found, to read additional folders passed as argument, indeed.

**Comment by bilelmoussaoui** [comment]
That can improve things on my end as well so +1 from me

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/gtk-rs/gir/issues/1040. Closing this one then.

**Pull request closed without merging**
