### PR TITLE
Reformat

### PR DESCRIPTION
**Pull request by EPashkin**
Added script that run xmlstarlet to all *.gir files after download to minimize changes from fix.sh

cc @GuillaumeGomez, @sdroege

cc @antoyo as WebKit2-4.0.gir also updated

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Huge :+1: !

**Comment by sdroege** [comment]
Sure, go for it

**Comment by antoyo** [comment]
Approved.

**Comment by GuillaumeGomez** [comment]
Then I merge. Thanks @EPashkin!

**Pull request merged**
