### PR TITLE
Download from eoan instead of disco

### PR DESCRIPTION
**Pull request by moggiesir**
Webkit and JavaScriptCore no longer have mirrors.kernel.org links on their gir download pages for disco, so this switches to fetch from eoan instead.

Most of the diffs are due to additional docs/source-position info.

### CODE REVIEW

**Comment by EPashkin** [comment]
Thanks, looks very good for me, but it need more checks,
so sorry, but IMHO this PR and #36 will be postponed for while because we have release under way.

**Comment by moggiesir** [comment]
Ok, thanks for the info.

What do you mean but a "while"? Days/weeks/months? I'm working towards adding bindings for all of javascriptcore: https://github.com/gtk-rs/javascriptcore-rs/compare/master...moggiesir:edge

**Comment by EPashkin** [comment]
I hope that "while" meant "days" https://github.com/gtk-rs/release/issues/73#issuecomment-498829850

Thanks for work on javascriptcore-rs

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege IMHO this PR is ready to merge,
please look at resulting sys changes https://github.com/gtk-rs/sys/pull/138

**Comment by GuillaumeGomez** [comment]
Seems like `gdk-sys` was not correctly generated.

**Pull request merged**
