### PR TITLE
Update gir files to get latest improvements in g-ir-scanner.

### PR DESCRIPTION
**Pull request by tmiasko**
Since our last update there have been improvements in g-ir-scanner, which now
does a better job at preserving const specifiers. Upstream gir files are
already regenerated accordingly. It would be nice to have those in Rust
bindings as well. (Note that we are still using the same Ubuntu release for gir
files).

### CODE REVIEW

**Comment by EPashkin** [comment]
@tmiasko Thanks
I can't find actual cases IMHO we need script `empty_fix.sh` that run `xmlstarlet ed -P -L` without doing actual changes, and run it in commits like "Update gir files (without any modifications)." to minimize changes.
Or I don't find cases because you already applied it?

cc @GuillaumeGomez, @sdroege too

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/gir-files/pull/20/commits/e5546062284e84bce72ae1328ce74363141146b2#diff-207a93126e1cfce21efdbe95b0ee77dfR19 unneeded diff I talk about

**Comment by tmiasko** [comment]
The best way to see the differences is to look at overall diff. (Changes have been made upstream, not in fix.sh).

If you want to avoid unnecessary differences introduced by separate commits, I can squash them as well, though I though that clean one would be useful as a starting point when doing changes to fix script.

**Comment by tmiasko** [comment]
Regarding overall noise in diffs in general I would propose either of those:

* Store only version with changes applied already.
* Store version without changes in a separate directory.

**Comment by tmiasko** [comment]
I squashed the commits.

**Comment by EPashkin** [comment]
@tmiasko Main reason for my request is that I wanted to check, which of our fixes done in upstream and can be removed already.

**Comment by EPashkin** [comment]
But it can wait for next update 😉

**Comment by GuillaumeGomez** [comment]
If it's good for @EPashkin, then it's good for me as well! Thanks!

**Comment by tmiasko** [comment]
Seems like a change in glib: https://bugzilla.gnome.org/show_bug.cgi?id=788863.

**Comment by EPashkin** [comment]
Very bad that it intentional, not sure what to do on Gir side.
Gio affected too `g_app_info_create_from_commandline`, `g_app_launch_context_setenv`,

**Comment by sdroege** [comment]
These should probably become OsString on our side. And maybe just remove the env variable API, std has better API for the same

**Pull request merged**
