### PR TITLE
Obliterate unnecessary (trailing) whitespace

### PR DESCRIPTION
**Pull request by MarijnS95**
As requested in https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/676#note_744649

Note that this PR is _excessively large_. New files have been imported because whitespace cleanup (ie. converting an empty element from `<foo>** newlines **</foo>` to `<foo />`) only happens when the deletion operation `ed -d` runs (without `-P`). Nothing is reformatted if the contents of `<foo>` were already removed.

Luckily only Gdk-Pixbuf appears to be affected with some removals, apparently because a git version was imported just 3 days ago. Reimported that, and the end-result is nil: https://github.com/gtk-rs/gtk-rs/compare/master...MarijnS95:drop-whitespace

EDIT:

```
 39 files changed, 4775 insertions(+), 44576 deletions(-)
```
That says quite enough :sweat_smile:

### CODE REVIEW

**Comment by sdroege** [comment]
```
Run ./gir/target/release/gir -c sys/conf/gir-gtk4.toml -m sys -o sys/gtk4-sys/ -d .
[WARN  libgir::parser] <boxed name=Some("FileList")>
GirXml: ./Gsk-4.0.gir at line 1890:11: <type> element is missing a name attribute
Error: Process completed with exit code 1.
```

I think there were some manual changes... @bilelmoussaoui @BrainBlasted? :)

**Review by sdroege — COMMENTED** [review]
Looks good to me otherwise

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
> ```
> Run ./gir/target/release/gir -c sys/conf/gir-gtk4.toml -m sys -o sys/gtk4-sys/ -d .
> [WARN  libgir::parser] <boxed name=Some("FileList")>
> GirXml: ./Gsk-4.0.gir at line 1890:11: <type> element is missing a name attribute
> Error: Process completed with exit code 1.
> ```
> 
> I think there were some manual changes... @bilelmoussaoui @BrainBlasted? :)

Everything was added to the fix.sh script

**Comment by MarijnS95** [comment]
@bilelmoussaoui the files have been freshly downloaded with `./dl.sh` and `./fix.sh` has also been ran. Would you mind taking a look what happens and why?

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui the files have been freshly downloaded with `./dl.sh` and `./fix.sh` has also been ran. Would you mind taking a look what happens and why?

I would remove the gtk4 stuff from dl.sh script for now, the download script uses debian and I'm not sure if they have the latest release of GTK4 already or not. I will have a closer look later today

**Comment by bilelmoussaoui** [comment]
From a quick look at the changes, it seems the debian package is still outdated; which is the reason of the build failure. There were some broken elements in 3.99.5 which were fixed in 4.0.0 and hence were removed from the fix.sh script.

**Comment by MarijnS95** [comment]
@bilelmoussaoui Can I pull a more recent file from a CI somewhere? I had to to the same for `GdkPixbuf`, also without botching `./dl.sh` temporarily.

Though it might be wise to disable both downloads for the time being, to not confuse future updates.

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui Can I pull a more recent file from a CI somewhere? I had to to the same for `GdkPixbuf`, also without botching `./dl.sh` temporarily.
> 
> Though it might be wise to disable both downloads for the time being, to not confuse future updates.

I have built gtk4 locally on a docker image and used the gir files from there; the same docker image is what I use for the CI in gtk4-rs repository

**Comment by MarijnS95** [comment]
@bilelmoussaoui gtk4-rs only seems to have GH actions, and I don't think it has the original, uncleaned gir files anyway (it uses them from the gir-files repo directly after all).

Ended up cloning and building gtk4-rs (ThreadRippers are the best invention ever), looks like the CI succeeds now. Diff here: https://github.com/MarijnS95/gtk4-rs/compare/drop-whitespace

Shall I submit PRs for both gtk's from those branches when this is merged?

**Pull request merged**
