### PR TITLE
Update gir files to focal

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Does this have to be merged before updating gtk-rs/sys? also, once both this and a future update to the sys crate get merged, should I re-generate the bindings of all the other crates or is that something that is done as part of the release process?

**Comment by sdroege** [comment]
> should I re-generate the bindings of all the other crates

See above, @EPashkin already did some of them. It should be done as part of this PR to make sure things don't just fall apart, and there's also various new API to be added (autogenerated) as part of this update so it's good to have this done not as part of the release process because things can fail.

**Comment by bilelmoussaoui** [comment]
aha makes sense, @EPashkin which ones you want some help with?

**Comment by EPashkin** [comment]
@bilelmoussaoui 
After we decide if we needed `atk_plug_set_child` from unstable v2_35 or not and this PR is merged,
only last changed is glib if you want do it.

**Comment by bilelmoussaoui** [comment]
Sure, I'm going to take care of the glib one

**Comment by sdroege** [comment]
>  only last changed is glib if you want do it.

gio also has changes

**Comment by EPashkin** [comment]
Oh, yes, I prepared PR for gio too but not pushed it

**Comment by EPashkin** [comment]
@sdroege , @GuillaumeGomez 
So last problem here: we remove `atk_plug_set_child` from unstable v2_35 or not?

**Comment by sdroege** [comment]
>  So last problem here: we remove `atk_plug_set_child` from unstable v2_35 or not?

Yes

**Comment by bilelmoussaoui** [comment]
glib is done here https://github.com/gtk-rs/glib/pull/653

**Comment by EPashkin** [comment]
@bilelmoussaoui Please remove `atk_plug_set_child` with `fix.sh` it enough to remove `feature = "v2_35"` in sys too.

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui Please remove `atk_plug_set_child` with `fix.sh` it enough to remove `feature = "v2_35"` in sys too.

My regex skills are pretty low, but with something like 
```
xmlstarlet ed -P -L \
  -d '//*[@c:identifier="atk_plug_set_child"]/*' \
  Atk-1.0.gir
```
it just removes the node's content and not the node itself; do you have an idea on how to "fix" it? :)

**Comment by EPashkin** [comment]
Only last `/*` was unneeded:
```
# remove function from v2_35
xmlstarlet ed -P -L \
  -d '///_:method[@c:identifier="atk_plug_set_child"]' \
  Atk-1.0.gir
```
note: has /// due windows bug, IMHO work same for you too.

**Comment by bilelmoussaoui** [comment]
@EPashkin thanks

This one should be ready to go then:)

**Comment by EPashkin** [comment]
@bilelmoussaoui Thanks you too. 
👍

**Comment by GuillaumeGomez** [comment]
Ping me once CI passes so I can merge.

**Comment by bilelmoussaoui** [comment]
@GuillaumeGomez it's green :+1:

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
