### PR TITLE
Import updated `Vulkan-1.0.gir`

### PR DESCRIPTION
**Pull request by MarijnS95**
https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/427

This is needed for generating Vulkan code in GStreamer.

### CODE REVIEW

**Comment by sdroege** [comment]
The gir files are automatically pulled in from the GNOME SDK. So once your MR to gobject-introspection is merged, this should be updated on the next run, or am I missing something?

**Comment by MarijnS95** [comment]
No you did not miss anything, I simply wasn't aware and didn't want to figure out as this is already on a tangent of a tangent of a tangent (repeat a few times more) of hopefully landing the GStreamer Vulkan bindings some day. It's been way too long and I needed to push this branch anyway for my gstreamer-rs fork to point to and generate correctly.

**Comment by sdroege** [comment]
As the general update PR (https://github.com/gtk-rs/gir-files/pull/181) is currently blocked by some unrelated infrastructure issues, I think we could also merge this one here separately for the time being once that gobject-introspection MR is merged.

**Comment by MarijnS95** [comment]
Thanks, but let's wait and see how the upstream gobject-introspection MR goes first.

I might need more information for gir to tell handles and structs (and whether they have pointers) apart anyway.

**Comment by MarijnS95** [comment]
@sdroege I could help with a push on https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/427, to actually get this file bumped to the correct state.

**Pull request closed without merging**
