### PR TITLE
Update glib gir to 2.63.5

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Part of https://github.com/gtk-rs/glib/pull/585/

### CODE REVIEW

**Comment by EPashkin** [comment]
@bilelmoussaoui Sorry, but this PR also won't be merged.
Update need be made by 'dl.sh' that update all girs.
We made attempt to get more fresh girs in #47, but it failed.
Last ubuntu's version in focal is glb2.63.3-3 (not sure why it published with odd number).

Also  https://github.com/gtk-rs/glib/pull/585#issuecomment-583532617 still valid

**Comment by bilelmoussaoui** [comment]
Got it. So I will close this until there's something that can be updated with the dl.sh script.

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege 
Seems pango in `ubuntu focal` also broken: it have ` <type c:type="hb_feature_t"/>` but no new type for `hb_feature_t` defined. Future is grim.
Also its glib have `g_get_os_info`

**Comment by GuillaumeGomez** [comment]
Then it needs to be reported upstream. If someone can do it, it'd be awesome. :)

**Comment by sdroege** [comment]
Yeah and ideally this should be reported before the next round of stable releases, or otherwise we can't update to them. Please put a link here once done.

**Comment by bilelmoussaoui** [comment]
Done https://gitlab.gnome.org/GNOME/pango/issues/458.

**Pull request closed without merging**
