### PR TITLE
Get latest gir files version

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @sdroege @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
Seems dl.sh not finished correctly and reformat.sh not called.

**Comment by EPashkin** [comment]
Also seems gir need support (or ignore) new tag `function-macro`
```
    <function-macro name="ALIGNOF"
                    c:identifier="G_ALIGNOF"
                    version="2.60"
                    introspectable="0">
```

**Comment by GuillaumeGomez** [comment]
I'm sending a PR to ignore it.

**Comment by EPashkin** [comment]
IMHO first problem is not fixed. Try run  reformat.sh

**Comment by GuillaumeGomez** [comment]
Arf indeed, sorry, completely slipped out of my mind...

**Comment by GuillaumeGomez** [comment]
Ok, should be complete now. I wonder why it didn't finish correctly the first time...

**Comment by sdroege** [comment]
Good for me as long as -sys can be generated successfully and doesn't fall apart.

Now you only need to regenerate all the crates (and please remove glib re-exports and add dependency prelude re-exports) :)

**Comment by GuillaumeGomez** [comment]
Yes. T_T

**Comment by EPashkin** [comment]
@GuillaumeGomez as you forgot to run "./fix.sh" too, seems this repo need normal readme too.

**Comment by GuillaumeGomez** [comment]
Indeed, adding one. Sorry for the mess...

**Comment by GuillaumeGomez** [comment]
And done as well. Did I forget something else?

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks, LGFM.

**Pull request merged**
