### PR TITLE
Fix invalid gir content

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
From where this fix?
https://packages.ubuntu.com/artful/amd64/libpango1.0-dev
and https://packages.ubuntu.com/artful/amd64/libgirepository1.0-dev
don't have it.

**Comment by EPashkin** [comment]
If this fix only for some crate then we normally make patch in gir.

**Comment by GuillaumeGomez** [comment]
I did it by hand. Too annoying otherwise.

**Comment by EPashkin** [comment]
Maybe we need update `dl.sh` to patch files?
Otherwise changes will be reversed on next update

**Comment by GuillaumeGomez** [comment]
I know, I was thinking about writing a script to just patch those 2 `.gir` files.

**Comment by GuillaumeGomez** [comment]
So for the `grep` error, it's simply because BSD's `grep` is different (yeay...). Otherwise I added a script to fix the errors when we update the files. Does it seem good to you @EPashkin?

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks, it works fine.
Only strange why you don't use `patch`.
Bad that you can't reload other files, it has many changes.
Maybe `gir-dl.sh` need changed to python too

**Comment by GuillaumeGomez** [comment]
`patch` seemed like more work for not much benefits.

> Maybe `gir-dl.sh` need changed to python too

Maybe, but it'll be for another day. :)

**Pull request merged**
