### PR TITLE
Fix GtkIconSize usage

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gtk/issues/439

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
Changes in sys https://github.com/gtk-rs/sys/compare/master...EPashkin:fix_GtkIconSize_usage?expand=1
and in gtk https://github.com/gtk-rs/gtk/compare/master...EPashkin:fix_GtkIconSize_usage?expand=1

**Comment by GuillaumeGomez** [comment]
Nice catch, thanks!

**Comment by EPashkin** [comment]
I also added function for simplify usage when parameter has comment like "A size of `(GtkIconSize) -1` means render at the size of the source and don't scale".
```
impl IconSize {
    pub fn new_dont_scale() -> IconSize {
        IconSize::__Unknown(-1)
    }
}
```

**Comment by sdroege** [comment]
:+1:, also the -sys and gtk changes. I would call the helper function there `IconSize::unscaled()`

**Comment by EPashkin** [comment]
`IconSize::unscaled()` is better that my.

**Comment by sdroege** [comment]
Ok, go for it then :)

**Comment by EPashkin** [comment]
I will do final update: change `gtk_icon_set_get_sizes` too as from `gtk-sys` or C side it will be equivalent anyway.

**Comment by EPashkin** [comment]
Updated

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
