### PR TITLE
Add Rsvg from http://packages.ubuntu.com/zesty/amd64/librsvg2-dev

### PR DESCRIPTION
**Pull request by selaux**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
cc @EPashkin

**Comment by EPashkin** [comment]
Currently all updates better get from Artful
Also we really need these packages in this repo?

**Comment by GuillaumeGomez** [comment]
I wonder as well...

**Comment by bilelmoussaoui** [comment]
rsvg is now written in rust, there is no need to use it from it bindings

**Pull request closed without merging**
