### PR TITLE
Update script to download Ubuntu Disco packages

### PR DESCRIPTION
**Pull request by EPashkin**
This will need changes in manual code in glib, [gdk](https://github.com/gtk-rs/gdk/pull/259) for ToGlibContainerFromSlice<*const>.

FcFontMap was removed from pangocairo

Other affected crates: atk, sourceview, gio, pango, gtk

This is WIP as I don't want stall glibwrapper and closures updates.

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Looks good to me. 👍

**Comment by sdroege** [comment]
:+1: too. Does gir like the new .gir files?

**Comment by EPashkin** [comment]
All build fine with some manual changes, Ex. GClosureMarshal accept const param_values now.
```diff
 pub type GClassFinalizeFunc = Option<unsafe extern "C" fn(gpointer, gpointer)>;
 pub type GClassInitFunc = Option<unsafe extern "C" fn(gpointer, gpointer)>;
-pub type GClosureMarshal = Option<unsafe extern "C" fn(*mut GClosure, *mut GValue, c_uint, *mut GValue, gpointer, gpointer)>;
+pub type GClosureMarshal = Option<unsafe extern "C" fn(*mut GClosure, *mut GValue, c_uint, *const GValue, gpointer, gpointer)>;
 pub type GClosureNotify = Option<unsafe extern "C" fn(gpointer, *mut GClosure)>;
 pub type 
```

**Comment by sdroege** [comment]
Sounds good to me

**Comment by EPashkin** [comment]
This need merged first then I can update non merged PRs and add with gir-files submodule update

**Comment by GuillaumeGomez** [comment]
Ok!

**Pull request merged**
