### PR TITLE
Add gtk4 files

### PR DESCRIPTION
**Pull request by sfanxiang**

### CODE REVIEW

**Comment by sfanxiang** [comment]
cc @GuillaumeGomez @sdroege

**Comment by sdroege** [comment]
Looks good to me. What's missing here, why is it WIP? :)

**Comment by GuillaumeGomez** [comment]
Looks good to me as well.

> What's missing here, why is it WIP? :)

Now I'm scared.

**Comment by sfanxiang** [comment]
@sdroege @GuillaumeGomez The download is not automated in `dl.sh` (they don't have gtk4 yet). Apart from that, I don't have anything else currently in mind.

**Comment by alatiera** [comment]
What ref/tag where the gir files build from? (just curious).

I think its fine if updating them is manual till the first rc/releases of gtk4.

**Comment by sfanxiang** [comment]
@alatiera I believe it was e0e9d8c6b55380d540420a47eaeabb6d608a835b for gtk4.

**Comment by sdroege** [comment]
Let's document the versions in the commit message and then get it in :)

**Comment by sfanxiang** [comment]
@sdroege versions documented.

**Comment by sdroege** [comment]
Good to go for me then!

**Comment by GuillaumeGomez** [comment]
\~o\~

**Pull request merged**
