### PR TITLE
Add the IBus gir file

### PR DESCRIPTION
**Pull request by bochecha**
I'm working my way through this whole thing, with the goal of eventually being able to write an IBus engine in Rust.

This seems like the first step, so here goes. :slightly_smiling_face:

### CODE REVIEW

**Comment by bochecha** [comment]
As I understand it, it's needed in order to make an ibus-sys and an ibus crate.

It is very possible I misunderstood though, as I found the documentation for this whole stack a bit lacking. :confused:

**Comment by EPashkin** [comment]
@bochecha IMHO You need only .gir files for IBus and it dependencies: gio, glib, gobject and can store there 4 files in your repo like gstreamer (https://gitlab.freedesktop.org/slomo/gstreamer-rs/tree/master/gir-files).

**Comment by GuillaumeGomez** [comment]
No, you don't need to (at least not into this repository). You need to have the gir files though. Just clone our gir-files and put your gir file into it. Then you can generate the sys part (and then the crate itself). Most of the steps are explained into the gir readme file. Take a look there. If you have more precise questions, don't hesitate to ask though!

**Comment by bochecha** [comment]
> Most of the steps are explained into the gir readme file.

That's where I looked.

The thing is that the "sys" repo then uses the "gir-files" repo as a submodule, so I found I had to change the submodule to point it to my fork where I added the IBus gir file.

It's convoluted, so adding it to this repo would have made it much easier.

Also, this repo looks like a gathering of all the gir files that the community has found useful, put together to share the maintenance and upgrade them in sync.

> IMHO You need only .gir files for IBus and it dependencies: gio, glib, gobject and can store there 4 files in your repo like gstreamer

Ok, so the solution is to put my sys crate in my own repo, not have it as part of the "sys" repo from this organization?

The way the community is structured, it led me to believe that the goal was to put all the -sys crates in the same repo so they are maintained together and kept in sync.

It's possible I had wrong expectations, but there was no documentation I could find on the community norms and the goals for shared maintenance and contributions, so I was left assuming.

> If you have more precise questions, don't hesitate to ask though!

I guess what I found missing is recommendations for what to do when you need a new GI-based library. Not the technical process (that's mostly explained in the gir README indeed), but the community/organization process.

Are new crates wanted in this organization or should they be maintained separately? Are there criteria for which crates you'd accept and which you'd prefer kept outside?

What would be a good way to organize the crates/repositories in a way that will make it easier to maintain outside of this organization? (the gstreamer example would be a good resource I suppose, thanks for that)

I realize this isn't the right place to ask though, but that's where the conversation was started. I'll be happy to move this to a dedicated issue or to IRC if you prefer. :slightly_smiling_face:

**Comment by GuillaumeGomez** [comment]
> The thing is that the "sys" repo then uses the "gir-files" repo as a submodule, so I found I had to change the submodule to point it to my fork where I added the IBus gir file.
>
> It's convoluted, so adding it to this repo would have made it much easier.

You just need a `gir-files` repository with the gir files you need inside it and that's it.

> Also, this repo looks like a gathering of all the gir files that the community has found useful, put together to share the maintenance and upgrade them in sync.

It only contains files needed by gtk-rs crates.

> Are new crates wanted in this organization or should they be maintained separately? Are there criteria for which crates you'd accept and which you'd prefer kept outside?

So basically, it depends mostly on what users want. If enough users want it, I consider it, I propose it to the other members and if enough of them accept, we integrate it into the organization. However, it's not really official or anything.

> What would be a good way to organize the crates/repositories in a way that will make it easier to maintain outside of this organization? (the gstreamer example would be a good resource I suppose, thanks for that)

Gstreamer is a good example indeed. If you intend to have multiple crates, then I recommend you to fork gir-files and then to maintain your fork with your adds.

> I realize this isn't the right place to ask though, but that's where the conversation was started. I'll be happy to move this to a dedicated issue or to IRC if you prefer. 🙂

I'm fine with it. Also, I won't be on IRC for the next two weeks (looooooow internet connection) but we can talk about it later on (maybe some other gtk-rs members will be present though, not sure 😉).

**Comment by bochecha** [comment]
>> Are new crates wanted in this organization or should they be maintained separately? Are there criteria for which crates you'd accept and which you'd prefer kept outside?
> 
> So basically, it depends mostly on what users want. If enough users want it, I consider it, I propose it to the other members and if enough of them accept, we integrate it into the organization. However, it's not really official or anything.

Alright, so consider this a use wanting an ibus crate (which I'm trying to work on), in case you find enough other users wanting it. :slightly_smiling_face:

I would respectfully suggest you write down some of the things we talked about here, to avoid future newcomers making the same wrong assumptions as I did.

In any case, I guess we can close this.

**Comment by GuillaumeGomez** [comment]
I intend to write a small tutorial on how to create a gnome library binding
using gir on the gtk-rs website. Maybe add a section on how such processes
work would be nice too indeed. Thanks for taking the time to talk about it
with us! :)

Le mar. 25 déc. 2018 à 21:52, Mathieu Bridon <notifications@github.com> a
écrit :

**Comment by bilelmoussaoui** [comment]
I am going to close this one as it is not really part of the "core" gir files. It is better to keep the gir file along the bindings unless a lot of other bindings would make use of it.

**Pull request closed without merging**
