### PR TITLE
Update to Ubuntu Groovy files and redownload

### PR DESCRIPTION
**Pull request by BrainBlasted**
Updates all files with the latest versions from Ubuntu
Groovy.

Supersedes https://github.com/gtk-rs/gir-files/pull/56

### CODE REVIEW

**Comment by BrainBlasted** [comment]
Need to test for each lib:

* [ ] Gdk-4.0
* [ ] GdkX11-4.0
* [ ] Gsk-4.0
* [ ] Gtk-4.0
* [ ] JavaScriptCore-4.0
* [ ] WebKit2-4.0

**Comment by BrainBlasted** [comment]
Need to test for each lib:

* [ ] Gdk-4.0
* [ ] GdkX11-4.0
* [ ] Gsk-4.0
* [ ] Gtk-4.0
* [ ] JavaScriptCore-4.0
* [ ] WebKit2-4.0

**Comment by sdroege** [comment]
TODO list:

* Regenerate sys and check if all looks good and it also builds
* Regenerate glib, gio, pango, gdk and gtk and ---^
* Add new API as needed (can be a separate PR)

**Comment by bilelmoussaoui** [comment]
- pango: https://github.com/gtk-rs/pango/pull/197
- gdk: https://github.com/gtk-rs/gdk/pull/360

**Comment by sdroege** [comment]
Where do the GTK4 .gir files come from btw?

**Comment by BrainBlasted** [comment]
The GTK4 gir file itself was pulled via debian from dl.sh; I should probably go through and pull all of those from the GNOME nightly, right?

**Comment by sdroege** [comment]
> The GTK4 gir file itself was pulled via debian from dl.sh; I should probably go through and pull all of those from the GNOME nightly SDK, right?

Nightly is using development versions or not? That seems suboptimal, we should only ever pull in stable releases :)

**Comment by BrainBlasted** [comment]
Should I try to get the gir files manually building from the tags, then? I don't think GTK4 is in the 3.38 SDK

**Comment by sdroege** [comment]
For GTK4 until 4.0.0 this seems fine, just not for all the others that have stable releases :)

**Review by sdroege — APPROVED** [review]
The generated things look good to me, let's get this in @GuillaumeGomez :)

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
